CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY, email VARCHAR(320) UNIQUE NOT NULL, display_name VARCHAR(80) NOT NULL, password_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS trips (id UUID PRIMARY KEY, owner_id UUID NOT NULL REFERENCES users(id), title VARCHAR(160) NOT NULL, destination VARCHAR(160) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS expenses (id UUID PRIMARY KEY, trip_id UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE, paid_by UUID NOT NULL, amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0), description VARCHAR(240) NOT NULL);
CREATE TABLE IF NOT EXISTS matrix_nodes (id UUID PRIMARY KEY, trip_id UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE, label VARCHAR(160) NOT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL);
CREATE INDEX IF NOT EXISTS trips_owner_idx ON trips(owner_id);
CREATE INDEX IF NOT EXISTS expenses_trip_idx ON expenses(trip_id);
