apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: globetrek
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  ingressClassName: nginx
  tls:
    - hosts: [globetrek.example.com]
      secretName: globetrek-tls
  rules:
    - host: globetrek.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend: { service: { name: globetrek-backend, port: { number: 8000 } } }
